version: '3.3'

networks:
  nginx-proxy:
    external: false
    # name: nginx-proxy

services:

  db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'crud-application'
    ports:
    - 3306:3306

  # python-app:
    # image: 95osama123/fixed_task:1.0
    # ports:
      # - "8090:3306"
    # restart: always
    # networks:
      # - nginx-proxy
    # depends_on:
      # - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
    - 8081:80
  environment:        
    PMA_HOST: mysql-db
